# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token a20b83f25afbb97b048be42b616f98df36a9cf3c

{
  "title": "машина4",
  "description": "ржавая"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/14/
Content-Type: application/json
Authorization: Token 38ae15949b890ee6b72460fd481475e057ba7616

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=4
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_after=2020-10-01
Content-Type: application/json
